// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TKC_MDS.Models
{
    public partial class Q_SchCustomer
    {
        public string CustID { get; set; }
        public string CustName { get; set; }
    }
}