// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TKC_MDS.Models
{
    public partial class T_SchDataType_Cust
    {
        public string CustID { get; set; }
        public string TypeCode { get; set; }
        public bool DeleteOld { get; set; }
        public bool SepMDSbyFlag01 { get; set; }
        public bool FirmOrder { get; set; }
        public bool MakeMDS { get; set; }
        public bool ShowInSch { get; set; }
        public string MixedSchWith { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public bool RowManyDue { get; set; }
        public bool ManyDueType { get; set; }
        public int ManyDueDataNo { get; set; }
        public int ManyDueSetNo { get; set; }
        public int ManyDueDataLong { get; set; }
        public bool? ForPOS { get; set; }
        public string Note { get; set; }
    }
}